apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykubeapp
spec:
  selector:
    matchLabels:
      app: mykubeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mykubeapp
    spec:
      containers:
      - name: mykubeapp
        image: tomcoolpxl/mykubeapp:1.0
        ports:
        - containerPort: 8080
